[package]
name = "normal_game_jam_2024"
version = "0.1.0"
authors = ["bogay <pojay11523@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
cpal = "0.15.3"
crossterm = "0.27.0"
ratatui = "0.26.0"
vosk = "0.2.0"

[build-dependencies]
bindgen = "0.65.1"
